/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import es.davinciti.liferay.model.LineaGastoProyecto;
import es.davinciti.liferay.service.LineaGastoProyectoService;
import es.davinciti.liferay.service.persistence.ApplicationStatusPersistence;
import es.davinciti.liferay.service.persistence.CalendarioPersistence;
import es.davinciti.liferay.service.persistence.ConnectionActionTypesPersistence;
import es.davinciti.liferay.service.persistence.ConnectionConfigsPersistence;
import es.davinciti.liferay.service.persistence.ConnectionDataPersistence;
import es.davinciti.liferay.service.persistence.ConnectionTypesPersistence;
import es.davinciti.liferay.service.persistence.CurrenciesCompanyPersistence;
import es.davinciti.liferay.service.persistence.CurrencyPersistence;
import es.davinciti.liferay.service.persistence.DiasVacacionesPersistence;
import es.davinciti.liferay.service.persistence.HistoricoNotaPersistence;
import es.davinciti.liferay.service.persistence.LineaGastoCategoriaPersistence;
import es.davinciti.liferay.service.persistence.LineaGastoClientePersistence;
import es.davinciti.liferay.service.persistence.LineaGastoFamiliaPersistence;
import es.davinciti.liferay.service.persistence.LineaGastoPayModePersistence;
import es.davinciti.liferay.service.persistence.LineaGastoPersistence;
import es.davinciti.liferay.service.persistence.LineaGastoProyectoPersistence;
import es.davinciti.liferay.service.persistence.NotaGastoPersistence;
import es.davinciti.liferay.service.persistence.OrganizationSageCompanyPersistence;
import es.davinciti.liferay.service.persistence.SageEmployeePersistence;
import es.davinciti.liferay.service.persistence.SapEmployeePersistence;
import es.davinciti.liferay.service.persistence.TipoDiaCalendarPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the linea gasto proyecto remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link es.davinciti.liferay.service.impl.LineaGastoProyectoServiceImpl}.
 * </p>
 *
 * @author Cmes
 * @see es.davinciti.liferay.service.impl.LineaGastoProyectoServiceImpl
 * @see es.davinciti.liferay.service.LineaGastoProyectoServiceUtil
 * @generated
 */
public abstract class LineaGastoProyectoServiceBaseImpl extends BaseServiceImpl
	implements LineaGastoProyectoService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link es.davinciti.liferay.service.LineaGastoProyectoServiceUtil} to access the linea gasto proyecto remote service.
	 */

	/**
	 * Returns the application status local service.
	 *
	 * @return the application status local service
	 */
	public es.davinciti.liferay.service.ApplicationStatusLocalService getApplicationStatusLocalService() {
		return applicationStatusLocalService;
	}

	/**
	 * Sets the application status local service.
	 *
	 * @param applicationStatusLocalService the application status local service
	 */
	public void setApplicationStatusLocalService(
		es.davinciti.liferay.service.ApplicationStatusLocalService applicationStatusLocalService) {
		this.applicationStatusLocalService = applicationStatusLocalService;
	}

	/**
	 * Returns the application status remote service.
	 *
	 * @return the application status remote service
	 */
	public es.davinciti.liferay.service.ApplicationStatusService getApplicationStatusService() {
		return applicationStatusService;
	}

	/**
	 * Sets the application status remote service.
	 *
	 * @param applicationStatusService the application status remote service
	 */
	public void setApplicationStatusService(
		es.davinciti.liferay.service.ApplicationStatusService applicationStatusService) {
		this.applicationStatusService = applicationStatusService;
	}

	/**
	 * Returns the application status persistence.
	 *
	 * @return the application status persistence
	 */
	public ApplicationStatusPersistence getApplicationStatusPersistence() {
		return applicationStatusPersistence;
	}

	/**
	 * Sets the application status persistence.
	 *
	 * @param applicationStatusPersistence the application status persistence
	 */
	public void setApplicationStatusPersistence(
		ApplicationStatusPersistence applicationStatusPersistence) {
		this.applicationStatusPersistence = applicationStatusPersistence;
	}

	/**
	 * Returns the calendario local service.
	 *
	 * @return the calendario local service
	 */
	public es.davinciti.liferay.service.CalendarioLocalService getCalendarioLocalService() {
		return calendarioLocalService;
	}

	/**
	 * Sets the calendario local service.
	 *
	 * @param calendarioLocalService the calendario local service
	 */
	public void setCalendarioLocalService(
		es.davinciti.liferay.service.CalendarioLocalService calendarioLocalService) {
		this.calendarioLocalService = calendarioLocalService;
	}

	/**
	 * Returns the calendario remote service.
	 *
	 * @return the calendario remote service
	 */
	public es.davinciti.liferay.service.CalendarioService getCalendarioService() {
		return calendarioService;
	}

	/**
	 * Sets the calendario remote service.
	 *
	 * @param calendarioService the calendario remote service
	 */
	public void setCalendarioService(
		es.davinciti.liferay.service.CalendarioService calendarioService) {
		this.calendarioService = calendarioService;
	}

	/**
	 * Returns the calendario persistence.
	 *
	 * @return the calendario persistence
	 */
	public CalendarioPersistence getCalendarioPersistence() {
		return calendarioPersistence;
	}

	/**
	 * Sets the calendario persistence.
	 *
	 * @param calendarioPersistence the calendario persistence
	 */
	public void setCalendarioPersistence(
		CalendarioPersistence calendarioPersistence) {
		this.calendarioPersistence = calendarioPersistence;
	}

	/**
	 * Returns the connection action types local service.
	 *
	 * @return the connection action types local service
	 */
	public es.davinciti.liferay.service.ConnectionActionTypesLocalService getConnectionActionTypesLocalService() {
		return connectionActionTypesLocalService;
	}

	/**
	 * Sets the connection action types local service.
	 *
	 * @param connectionActionTypesLocalService the connection action types local service
	 */
	public void setConnectionActionTypesLocalService(
		es.davinciti.liferay.service.ConnectionActionTypesLocalService connectionActionTypesLocalService) {
		this.connectionActionTypesLocalService = connectionActionTypesLocalService;
	}

	/**
	 * Returns the connection action types remote service.
	 *
	 * @return the connection action types remote service
	 */
	public es.davinciti.liferay.service.ConnectionActionTypesService getConnectionActionTypesService() {
		return connectionActionTypesService;
	}

	/**
	 * Sets the connection action types remote service.
	 *
	 * @param connectionActionTypesService the connection action types remote service
	 */
	public void setConnectionActionTypesService(
		es.davinciti.liferay.service.ConnectionActionTypesService connectionActionTypesService) {
		this.connectionActionTypesService = connectionActionTypesService;
	}

	/**
	 * Returns the connection action types persistence.
	 *
	 * @return the connection action types persistence
	 */
	public ConnectionActionTypesPersistence getConnectionActionTypesPersistence() {
		return connectionActionTypesPersistence;
	}

	/**
	 * Sets the connection action types persistence.
	 *
	 * @param connectionActionTypesPersistence the connection action types persistence
	 */
	public void setConnectionActionTypesPersistence(
		ConnectionActionTypesPersistence connectionActionTypesPersistence) {
		this.connectionActionTypesPersistence = connectionActionTypesPersistence;
	}

	/**
	 * Returns the connection configs local service.
	 *
	 * @return the connection configs local service
	 */
	public es.davinciti.liferay.service.ConnectionConfigsLocalService getConnectionConfigsLocalService() {
		return connectionConfigsLocalService;
	}

	/**
	 * Sets the connection configs local service.
	 *
	 * @param connectionConfigsLocalService the connection configs local service
	 */
	public void setConnectionConfigsLocalService(
		es.davinciti.liferay.service.ConnectionConfigsLocalService connectionConfigsLocalService) {
		this.connectionConfigsLocalService = connectionConfigsLocalService;
	}

	/**
	 * Returns the connection configs remote service.
	 *
	 * @return the connection configs remote service
	 */
	public es.davinciti.liferay.service.ConnectionConfigsService getConnectionConfigsService() {
		return connectionConfigsService;
	}

	/**
	 * Sets the connection configs remote service.
	 *
	 * @param connectionConfigsService the connection configs remote service
	 */
	public void setConnectionConfigsService(
		es.davinciti.liferay.service.ConnectionConfigsService connectionConfigsService) {
		this.connectionConfigsService = connectionConfigsService;
	}

	/**
	 * Returns the connection configs persistence.
	 *
	 * @return the connection configs persistence
	 */
	public ConnectionConfigsPersistence getConnectionConfigsPersistence() {
		return connectionConfigsPersistence;
	}

	/**
	 * Sets the connection configs persistence.
	 *
	 * @param connectionConfigsPersistence the connection configs persistence
	 */
	public void setConnectionConfigsPersistence(
		ConnectionConfigsPersistence connectionConfigsPersistence) {
		this.connectionConfigsPersistence = connectionConfigsPersistence;
	}

	/**
	 * Returns the connection data local service.
	 *
	 * @return the connection data local service
	 */
	public es.davinciti.liferay.service.ConnectionDataLocalService getConnectionDataLocalService() {
		return connectionDataLocalService;
	}

	/**
	 * Sets the connection data local service.
	 *
	 * @param connectionDataLocalService the connection data local service
	 */
	public void setConnectionDataLocalService(
		es.davinciti.liferay.service.ConnectionDataLocalService connectionDataLocalService) {
		this.connectionDataLocalService = connectionDataLocalService;
	}

	/**
	 * Returns the connection data remote service.
	 *
	 * @return the connection data remote service
	 */
	public es.davinciti.liferay.service.ConnectionDataService getConnectionDataService() {
		return connectionDataService;
	}

	/**
	 * Sets the connection data remote service.
	 *
	 * @param connectionDataService the connection data remote service
	 */
	public void setConnectionDataService(
		es.davinciti.liferay.service.ConnectionDataService connectionDataService) {
		this.connectionDataService = connectionDataService;
	}

	/**
	 * Returns the connection data persistence.
	 *
	 * @return the connection data persistence
	 */
	public ConnectionDataPersistence getConnectionDataPersistence() {
		return connectionDataPersistence;
	}

	/**
	 * Sets the connection data persistence.
	 *
	 * @param connectionDataPersistence the connection data persistence
	 */
	public void setConnectionDataPersistence(
		ConnectionDataPersistence connectionDataPersistence) {
		this.connectionDataPersistence = connectionDataPersistence;
	}

	/**
	 * Returns the connection types local service.
	 *
	 * @return the connection types local service
	 */
	public es.davinciti.liferay.service.ConnectionTypesLocalService getConnectionTypesLocalService() {
		return connectionTypesLocalService;
	}

	/**
	 * Sets the connection types local service.
	 *
	 * @param connectionTypesLocalService the connection types local service
	 */
	public void setConnectionTypesLocalService(
		es.davinciti.liferay.service.ConnectionTypesLocalService connectionTypesLocalService) {
		this.connectionTypesLocalService = connectionTypesLocalService;
	}

	/**
	 * Returns the connection types remote service.
	 *
	 * @return the connection types remote service
	 */
	public es.davinciti.liferay.service.ConnectionTypesService getConnectionTypesService() {
		return connectionTypesService;
	}

	/**
	 * Sets the connection types remote service.
	 *
	 * @param connectionTypesService the connection types remote service
	 */
	public void setConnectionTypesService(
		es.davinciti.liferay.service.ConnectionTypesService connectionTypesService) {
		this.connectionTypesService = connectionTypesService;
	}

	/**
	 * Returns the connection types persistence.
	 *
	 * @return the connection types persistence
	 */
	public ConnectionTypesPersistence getConnectionTypesPersistence() {
		return connectionTypesPersistence;
	}

	/**
	 * Sets the connection types persistence.
	 *
	 * @param connectionTypesPersistence the connection types persistence
	 */
	public void setConnectionTypesPersistence(
		ConnectionTypesPersistence connectionTypesPersistence) {
		this.connectionTypesPersistence = connectionTypesPersistence;
	}

	/**
	 * Returns the currencies company local service.
	 *
	 * @return the currencies company local service
	 */
	public es.davinciti.liferay.service.CurrenciesCompanyLocalService getCurrenciesCompanyLocalService() {
		return currenciesCompanyLocalService;
	}

	/**
	 * Sets the currencies company local service.
	 *
	 * @param currenciesCompanyLocalService the currencies company local service
	 */
	public void setCurrenciesCompanyLocalService(
		es.davinciti.liferay.service.CurrenciesCompanyLocalService currenciesCompanyLocalService) {
		this.currenciesCompanyLocalService = currenciesCompanyLocalService;
	}

	/**
	 * Returns the currencies company remote service.
	 *
	 * @return the currencies company remote service
	 */
	public es.davinciti.liferay.service.CurrenciesCompanyService getCurrenciesCompanyService() {
		return currenciesCompanyService;
	}

	/**
	 * Sets the currencies company remote service.
	 *
	 * @param currenciesCompanyService the currencies company remote service
	 */
	public void setCurrenciesCompanyService(
		es.davinciti.liferay.service.CurrenciesCompanyService currenciesCompanyService) {
		this.currenciesCompanyService = currenciesCompanyService;
	}

	/**
	 * Returns the currencies company persistence.
	 *
	 * @return the currencies company persistence
	 */
	public CurrenciesCompanyPersistence getCurrenciesCompanyPersistence() {
		return currenciesCompanyPersistence;
	}

	/**
	 * Sets the currencies company persistence.
	 *
	 * @param currenciesCompanyPersistence the currencies company persistence
	 */
	public void setCurrenciesCompanyPersistence(
		CurrenciesCompanyPersistence currenciesCompanyPersistence) {
		this.currenciesCompanyPersistence = currenciesCompanyPersistence;
	}

	/**
	 * Returns the currency local service.
	 *
	 * @return the currency local service
	 */
	public es.davinciti.liferay.service.CurrencyLocalService getCurrencyLocalService() {
		return currencyLocalService;
	}

	/**
	 * Sets the currency local service.
	 *
	 * @param currencyLocalService the currency local service
	 */
	public void setCurrencyLocalService(
		es.davinciti.liferay.service.CurrencyLocalService currencyLocalService) {
		this.currencyLocalService = currencyLocalService;
	}

	/**
	 * Returns the currency remote service.
	 *
	 * @return the currency remote service
	 */
	public es.davinciti.liferay.service.CurrencyService getCurrencyService() {
		return currencyService;
	}

	/**
	 * Sets the currency remote service.
	 *
	 * @param currencyService the currency remote service
	 */
	public void setCurrencyService(
		es.davinciti.liferay.service.CurrencyService currencyService) {
		this.currencyService = currencyService;
	}

	/**
	 * Returns the currency persistence.
	 *
	 * @return the currency persistence
	 */
	public CurrencyPersistence getCurrencyPersistence() {
		return currencyPersistence;
	}

	/**
	 * Sets the currency persistence.
	 *
	 * @param currencyPersistence the currency persistence
	 */
	public void setCurrencyPersistence(CurrencyPersistence currencyPersistence) {
		this.currencyPersistence = currencyPersistence;
	}

	/**
	 * Returns the dias vacaciones local service.
	 *
	 * @return the dias vacaciones local service
	 */
	public es.davinciti.liferay.service.DiasVacacionesLocalService getDiasVacacionesLocalService() {
		return diasVacacionesLocalService;
	}

	/**
	 * Sets the dias vacaciones local service.
	 *
	 * @param diasVacacionesLocalService the dias vacaciones local service
	 */
	public void setDiasVacacionesLocalService(
		es.davinciti.liferay.service.DiasVacacionesLocalService diasVacacionesLocalService) {
		this.diasVacacionesLocalService = diasVacacionesLocalService;
	}

	/**
	 * Returns the dias vacaciones remote service.
	 *
	 * @return the dias vacaciones remote service
	 */
	public es.davinciti.liferay.service.DiasVacacionesService getDiasVacacionesService() {
		return diasVacacionesService;
	}

	/**
	 * Sets the dias vacaciones remote service.
	 *
	 * @param diasVacacionesService the dias vacaciones remote service
	 */
	public void setDiasVacacionesService(
		es.davinciti.liferay.service.DiasVacacionesService diasVacacionesService) {
		this.diasVacacionesService = diasVacacionesService;
	}

	/**
	 * Returns the dias vacaciones persistence.
	 *
	 * @return the dias vacaciones persistence
	 */
	public DiasVacacionesPersistence getDiasVacacionesPersistence() {
		return diasVacacionesPersistence;
	}

	/**
	 * Sets the dias vacaciones persistence.
	 *
	 * @param diasVacacionesPersistence the dias vacaciones persistence
	 */
	public void setDiasVacacionesPersistence(
		DiasVacacionesPersistence diasVacacionesPersistence) {
		this.diasVacacionesPersistence = diasVacacionesPersistence;
	}

	/**
	 * Returns the historico nota local service.
	 *
	 * @return the historico nota local service
	 */
	public es.davinciti.liferay.service.HistoricoNotaLocalService getHistoricoNotaLocalService() {
		return historicoNotaLocalService;
	}

	/**
	 * Sets the historico nota local service.
	 *
	 * @param historicoNotaLocalService the historico nota local service
	 */
	public void setHistoricoNotaLocalService(
		es.davinciti.liferay.service.HistoricoNotaLocalService historicoNotaLocalService) {
		this.historicoNotaLocalService = historicoNotaLocalService;
	}

	/**
	 * Returns the historico nota remote service.
	 *
	 * @return the historico nota remote service
	 */
	public es.davinciti.liferay.service.HistoricoNotaService getHistoricoNotaService() {
		return historicoNotaService;
	}

	/**
	 * Sets the historico nota remote service.
	 *
	 * @param historicoNotaService the historico nota remote service
	 */
	public void setHistoricoNotaService(
		es.davinciti.liferay.service.HistoricoNotaService historicoNotaService) {
		this.historicoNotaService = historicoNotaService;
	}

	/**
	 * Returns the historico nota persistence.
	 *
	 * @return the historico nota persistence
	 */
	public HistoricoNotaPersistence getHistoricoNotaPersistence() {
		return historicoNotaPersistence;
	}

	/**
	 * Sets the historico nota persistence.
	 *
	 * @param historicoNotaPersistence the historico nota persistence
	 */
	public void setHistoricoNotaPersistence(
		HistoricoNotaPersistence historicoNotaPersistence) {
		this.historicoNotaPersistence = historicoNotaPersistence;
	}

	/**
	 * Returns the linea gasto local service.
	 *
	 * @return the linea gasto local service
	 */
	public es.davinciti.liferay.service.LineaGastoLocalService getLineaGastoLocalService() {
		return lineaGastoLocalService;
	}

	/**
	 * Sets the linea gasto local service.
	 *
	 * @param lineaGastoLocalService the linea gasto local service
	 */
	public void setLineaGastoLocalService(
		es.davinciti.liferay.service.LineaGastoLocalService lineaGastoLocalService) {
		this.lineaGastoLocalService = lineaGastoLocalService;
	}

	/**
	 * Returns the linea gasto remote service.
	 *
	 * @return the linea gasto remote service
	 */
	public es.davinciti.liferay.service.LineaGastoService getLineaGastoService() {
		return lineaGastoService;
	}

	/**
	 * Sets the linea gasto remote service.
	 *
	 * @param lineaGastoService the linea gasto remote service
	 */
	public void setLineaGastoService(
		es.davinciti.liferay.service.LineaGastoService lineaGastoService) {
		this.lineaGastoService = lineaGastoService;
	}

	/**
	 * Returns the linea gasto persistence.
	 *
	 * @return the linea gasto persistence
	 */
	public LineaGastoPersistence getLineaGastoPersistence() {
		return lineaGastoPersistence;
	}

	/**
	 * Sets the linea gasto persistence.
	 *
	 * @param lineaGastoPersistence the linea gasto persistence
	 */
	public void setLineaGastoPersistence(
		LineaGastoPersistence lineaGastoPersistence) {
		this.lineaGastoPersistence = lineaGastoPersistence;
	}

	/**
	 * Returns the linea gasto categoria local service.
	 *
	 * @return the linea gasto categoria local service
	 */
	public es.davinciti.liferay.service.LineaGastoCategoriaLocalService getLineaGastoCategoriaLocalService() {
		return lineaGastoCategoriaLocalService;
	}

	/**
	 * Sets the linea gasto categoria local service.
	 *
	 * @param lineaGastoCategoriaLocalService the linea gasto categoria local service
	 */
	public void setLineaGastoCategoriaLocalService(
		es.davinciti.liferay.service.LineaGastoCategoriaLocalService lineaGastoCategoriaLocalService) {
		this.lineaGastoCategoriaLocalService = lineaGastoCategoriaLocalService;
	}

	/**
	 * Returns the linea gasto categoria remote service.
	 *
	 * @return the linea gasto categoria remote service
	 */
	public es.davinciti.liferay.service.LineaGastoCategoriaService getLineaGastoCategoriaService() {
		return lineaGastoCategoriaService;
	}

	/**
	 * Sets the linea gasto categoria remote service.
	 *
	 * @param lineaGastoCategoriaService the linea gasto categoria remote service
	 */
	public void setLineaGastoCategoriaService(
		es.davinciti.liferay.service.LineaGastoCategoriaService lineaGastoCategoriaService) {
		this.lineaGastoCategoriaService = lineaGastoCategoriaService;
	}

	/**
	 * Returns the linea gasto categoria persistence.
	 *
	 * @return the linea gasto categoria persistence
	 */
	public LineaGastoCategoriaPersistence getLineaGastoCategoriaPersistence() {
		return lineaGastoCategoriaPersistence;
	}

	/**
	 * Sets the linea gasto categoria persistence.
	 *
	 * @param lineaGastoCategoriaPersistence the linea gasto categoria persistence
	 */
	public void setLineaGastoCategoriaPersistence(
		LineaGastoCategoriaPersistence lineaGastoCategoriaPersistence) {
		this.lineaGastoCategoriaPersistence = lineaGastoCategoriaPersistence;
	}

	/**
	 * Returns the linea gasto cliente local service.
	 *
	 * @return the linea gasto cliente local service
	 */
	public es.davinciti.liferay.service.LineaGastoClienteLocalService getLineaGastoClienteLocalService() {
		return lineaGastoClienteLocalService;
	}

	/**
	 * Sets the linea gasto cliente local service.
	 *
	 * @param lineaGastoClienteLocalService the linea gasto cliente local service
	 */
	public void setLineaGastoClienteLocalService(
		es.davinciti.liferay.service.LineaGastoClienteLocalService lineaGastoClienteLocalService) {
		this.lineaGastoClienteLocalService = lineaGastoClienteLocalService;
	}

	/**
	 * Returns the linea gasto cliente remote service.
	 *
	 * @return the linea gasto cliente remote service
	 */
	public es.davinciti.liferay.service.LineaGastoClienteService getLineaGastoClienteService() {
		return lineaGastoClienteService;
	}

	/**
	 * Sets the linea gasto cliente remote service.
	 *
	 * @param lineaGastoClienteService the linea gasto cliente remote service
	 */
	public void setLineaGastoClienteService(
		es.davinciti.liferay.service.LineaGastoClienteService lineaGastoClienteService) {
		this.lineaGastoClienteService = lineaGastoClienteService;
	}

	/**
	 * Returns the linea gasto cliente persistence.
	 *
	 * @return the linea gasto cliente persistence
	 */
	public LineaGastoClientePersistence getLineaGastoClientePersistence() {
		return lineaGastoClientePersistence;
	}

	/**
	 * Sets the linea gasto cliente persistence.
	 *
	 * @param lineaGastoClientePersistence the linea gasto cliente persistence
	 */
	public void setLineaGastoClientePersistence(
		LineaGastoClientePersistence lineaGastoClientePersistence) {
		this.lineaGastoClientePersistence = lineaGastoClientePersistence;
	}

	/**
	 * Returns the linea gasto familia local service.
	 *
	 * @return the linea gasto familia local service
	 */
	public es.davinciti.liferay.service.LineaGastoFamiliaLocalService getLineaGastoFamiliaLocalService() {
		return lineaGastoFamiliaLocalService;
	}

	/**
	 * Sets the linea gasto familia local service.
	 *
	 * @param lineaGastoFamiliaLocalService the linea gasto familia local service
	 */
	public void setLineaGastoFamiliaLocalService(
		es.davinciti.liferay.service.LineaGastoFamiliaLocalService lineaGastoFamiliaLocalService) {
		this.lineaGastoFamiliaLocalService = lineaGastoFamiliaLocalService;
	}

	/**
	 * Returns the linea gasto familia remote service.
	 *
	 * @return the linea gasto familia remote service
	 */
	public es.davinciti.liferay.service.LineaGastoFamiliaService getLineaGastoFamiliaService() {
		return lineaGastoFamiliaService;
	}

	/**
	 * Sets the linea gasto familia remote service.
	 *
	 * @param lineaGastoFamiliaService the linea gasto familia remote service
	 */
	public void setLineaGastoFamiliaService(
		es.davinciti.liferay.service.LineaGastoFamiliaService lineaGastoFamiliaService) {
		this.lineaGastoFamiliaService = lineaGastoFamiliaService;
	}

	/**
	 * Returns the linea gasto familia persistence.
	 *
	 * @return the linea gasto familia persistence
	 */
	public LineaGastoFamiliaPersistence getLineaGastoFamiliaPersistence() {
		return lineaGastoFamiliaPersistence;
	}

	/**
	 * Sets the linea gasto familia persistence.
	 *
	 * @param lineaGastoFamiliaPersistence the linea gasto familia persistence
	 */
	public void setLineaGastoFamiliaPersistence(
		LineaGastoFamiliaPersistence lineaGastoFamiliaPersistence) {
		this.lineaGastoFamiliaPersistence = lineaGastoFamiliaPersistence;
	}

	/**
	 * Returns the linea gasto pay mode local service.
	 *
	 * @return the linea gasto pay mode local service
	 */
	public es.davinciti.liferay.service.LineaGastoPayModeLocalService getLineaGastoPayModeLocalService() {
		return lineaGastoPayModeLocalService;
	}

	/**
	 * Sets the linea gasto pay mode local service.
	 *
	 * @param lineaGastoPayModeLocalService the linea gasto pay mode local service
	 */
	public void setLineaGastoPayModeLocalService(
		es.davinciti.liferay.service.LineaGastoPayModeLocalService lineaGastoPayModeLocalService) {
		this.lineaGastoPayModeLocalService = lineaGastoPayModeLocalService;
	}

	/**
	 * Returns the linea gasto pay mode remote service.
	 *
	 * @return the linea gasto pay mode remote service
	 */
	public es.davinciti.liferay.service.LineaGastoPayModeService getLineaGastoPayModeService() {
		return lineaGastoPayModeService;
	}

	/**
	 * Sets the linea gasto pay mode remote service.
	 *
	 * @param lineaGastoPayModeService the linea gasto pay mode remote service
	 */
	public void setLineaGastoPayModeService(
		es.davinciti.liferay.service.LineaGastoPayModeService lineaGastoPayModeService) {
		this.lineaGastoPayModeService = lineaGastoPayModeService;
	}

	/**
	 * Returns the linea gasto pay mode persistence.
	 *
	 * @return the linea gasto pay mode persistence
	 */
	public LineaGastoPayModePersistence getLineaGastoPayModePersistence() {
		return lineaGastoPayModePersistence;
	}

	/**
	 * Sets the linea gasto pay mode persistence.
	 *
	 * @param lineaGastoPayModePersistence the linea gasto pay mode persistence
	 */
	public void setLineaGastoPayModePersistence(
		LineaGastoPayModePersistence lineaGastoPayModePersistence) {
		this.lineaGastoPayModePersistence = lineaGastoPayModePersistence;
	}

	/**
	 * Returns the linea gasto proyecto local service.
	 *
	 * @return the linea gasto proyecto local service
	 */
	public es.davinciti.liferay.service.LineaGastoProyectoLocalService getLineaGastoProyectoLocalService() {
		return lineaGastoProyectoLocalService;
	}

	/**
	 * Sets the linea gasto proyecto local service.
	 *
	 * @param lineaGastoProyectoLocalService the linea gasto proyecto local service
	 */
	public void setLineaGastoProyectoLocalService(
		es.davinciti.liferay.service.LineaGastoProyectoLocalService lineaGastoProyectoLocalService) {
		this.lineaGastoProyectoLocalService = lineaGastoProyectoLocalService;
	}

	/**
	 * Returns the linea gasto proyecto remote service.
	 *
	 * @return the linea gasto proyecto remote service
	 */
	public es.davinciti.liferay.service.LineaGastoProyectoService getLineaGastoProyectoService() {
		return lineaGastoProyectoService;
	}

	/**
	 * Sets the linea gasto proyecto remote service.
	 *
	 * @param lineaGastoProyectoService the linea gasto proyecto remote service
	 */
	public void setLineaGastoProyectoService(
		es.davinciti.liferay.service.LineaGastoProyectoService lineaGastoProyectoService) {
		this.lineaGastoProyectoService = lineaGastoProyectoService;
	}

	/**
	 * Returns the linea gasto proyecto persistence.
	 *
	 * @return the linea gasto proyecto persistence
	 */
	public LineaGastoProyectoPersistence getLineaGastoProyectoPersistence() {
		return lineaGastoProyectoPersistence;
	}

	/**
	 * Sets the linea gasto proyecto persistence.
	 *
	 * @param lineaGastoProyectoPersistence the linea gasto proyecto persistence
	 */
	public void setLineaGastoProyectoPersistence(
		LineaGastoProyectoPersistence lineaGastoProyectoPersistence) {
		this.lineaGastoProyectoPersistence = lineaGastoProyectoPersistence;
	}

	/**
	 * Returns the nota gasto local service.
	 *
	 * @return the nota gasto local service
	 */
	public es.davinciti.liferay.service.NotaGastoLocalService getNotaGastoLocalService() {
		return notaGastoLocalService;
	}

	/**
	 * Sets the nota gasto local service.
	 *
	 * @param notaGastoLocalService the nota gasto local service
	 */
	public void setNotaGastoLocalService(
		es.davinciti.liferay.service.NotaGastoLocalService notaGastoLocalService) {
		this.notaGastoLocalService = notaGastoLocalService;
	}

	/**
	 * Returns the nota gasto remote service.
	 *
	 * @return the nota gasto remote service
	 */
	public es.davinciti.liferay.service.NotaGastoService getNotaGastoService() {
		return notaGastoService;
	}

	/**
	 * Sets the nota gasto remote service.
	 *
	 * @param notaGastoService the nota gasto remote service
	 */
	public void setNotaGastoService(
		es.davinciti.liferay.service.NotaGastoService notaGastoService) {
		this.notaGastoService = notaGastoService;
	}

	/**
	 * Returns the nota gasto persistence.
	 *
	 * @return the nota gasto persistence
	 */
	public NotaGastoPersistence getNotaGastoPersistence() {
		return notaGastoPersistence;
	}

	/**
	 * Sets the nota gasto persistence.
	 *
	 * @param notaGastoPersistence the nota gasto persistence
	 */
	public void setNotaGastoPersistence(
		NotaGastoPersistence notaGastoPersistence) {
		this.notaGastoPersistence = notaGastoPersistence;
	}

	/**
	 * Returns the organization sage company local service.
	 *
	 * @return the organization sage company local service
	 */
	public es.davinciti.liferay.service.OrganizationSageCompanyLocalService getOrganizationSageCompanyLocalService() {
		return organizationSageCompanyLocalService;
	}

	/**
	 * Sets the organization sage company local service.
	 *
	 * @param organizationSageCompanyLocalService the organization sage company local service
	 */
	public void setOrganizationSageCompanyLocalService(
		es.davinciti.liferay.service.OrganizationSageCompanyLocalService organizationSageCompanyLocalService) {
		this.organizationSageCompanyLocalService = organizationSageCompanyLocalService;
	}

	/**
	 * Returns the organization sage company remote service.
	 *
	 * @return the organization sage company remote service
	 */
	public es.davinciti.liferay.service.OrganizationSageCompanyService getOrganizationSageCompanyService() {
		return organizationSageCompanyService;
	}

	/**
	 * Sets the organization sage company remote service.
	 *
	 * @param organizationSageCompanyService the organization sage company remote service
	 */
	public void setOrganizationSageCompanyService(
		es.davinciti.liferay.service.OrganizationSageCompanyService organizationSageCompanyService) {
		this.organizationSageCompanyService = organizationSageCompanyService;
	}

	/**
	 * Returns the organization sage company persistence.
	 *
	 * @return the organization sage company persistence
	 */
	public OrganizationSageCompanyPersistence getOrganizationSageCompanyPersistence() {
		return organizationSageCompanyPersistence;
	}

	/**
	 * Sets the organization sage company persistence.
	 *
	 * @param organizationSageCompanyPersistence the organization sage company persistence
	 */
	public void setOrganizationSageCompanyPersistence(
		OrganizationSageCompanyPersistence organizationSageCompanyPersistence) {
		this.organizationSageCompanyPersistence = organizationSageCompanyPersistence;
	}

	/**
	 * Returns the sage employee local service.
	 *
	 * @return the sage employee local service
	 */
	public es.davinciti.liferay.service.SageEmployeeLocalService getSageEmployeeLocalService() {
		return sageEmployeeLocalService;
	}

	/**
	 * Sets the sage employee local service.
	 *
	 * @param sageEmployeeLocalService the sage employee local service
	 */
	public void setSageEmployeeLocalService(
		es.davinciti.liferay.service.SageEmployeeLocalService sageEmployeeLocalService) {
		this.sageEmployeeLocalService = sageEmployeeLocalService;
	}

	/**
	 * Returns the sage employee remote service.
	 *
	 * @return the sage employee remote service
	 */
	public es.davinciti.liferay.service.SageEmployeeService getSageEmployeeService() {
		return sageEmployeeService;
	}

	/**
	 * Sets the sage employee remote service.
	 *
	 * @param sageEmployeeService the sage employee remote service
	 */
	public void setSageEmployeeService(
		es.davinciti.liferay.service.SageEmployeeService sageEmployeeService) {
		this.sageEmployeeService = sageEmployeeService;
	}

	/**
	 * Returns the sage employee persistence.
	 *
	 * @return the sage employee persistence
	 */
	public SageEmployeePersistence getSageEmployeePersistence() {
		return sageEmployeePersistence;
	}

	/**
	 * Sets the sage employee persistence.
	 *
	 * @param sageEmployeePersistence the sage employee persistence
	 */
	public void setSageEmployeePersistence(
		SageEmployeePersistence sageEmployeePersistence) {
		this.sageEmployeePersistence = sageEmployeePersistence;
	}

	/**
	 * Returns the sap employee local service.
	 *
	 * @return the sap employee local service
	 */
	public es.davinciti.liferay.service.SapEmployeeLocalService getSapEmployeeLocalService() {
		return sapEmployeeLocalService;
	}

	/**
	 * Sets the sap employee local service.
	 *
	 * @param sapEmployeeLocalService the sap employee local service
	 */
	public void setSapEmployeeLocalService(
		es.davinciti.liferay.service.SapEmployeeLocalService sapEmployeeLocalService) {
		this.sapEmployeeLocalService = sapEmployeeLocalService;
	}

	/**
	 * Returns the sap employee remote service.
	 *
	 * @return the sap employee remote service
	 */
	public es.davinciti.liferay.service.SapEmployeeService getSapEmployeeService() {
		return sapEmployeeService;
	}

	/**
	 * Sets the sap employee remote service.
	 *
	 * @param sapEmployeeService the sap employee remote service
	 */
	public void setSapEmployeeService(
		es.davinciti.liferay.service.SapEmployeeService sapEmployeeService) {
		this.sapEmployeeService = sapEmployeeService;
	}

	/**
	 * Returns the sap employee persistence.
	 *
	 * @return the sap employee persistence
	 */
	public SapEmployeePersistence getSapEmployeePersistence() {
		return sapEmployeePersistence;
	}

	/**
	 * Sets the sap employee persistence.
	 *
	 * @param sapEmployeePersistence the sap employee persistence
	 */
	public void setSapEmployeePersistence(
		SapEmployeePersistence sapEmployeePersistence) {
		this.sapEmployeePersistence = sapEmployeePersistence;
	}

	/**
	 * Returns the tipo dia calendar local service.
	 *
	 * @return the tipo dia calendar local service
	 */
	public es.davinciti.liferay.service.TipoDiaCalendarLocalService getTipoDiaCalendarLocalService() {
		return tipoDiaCalendarLocalService;
	}

	/**
	 * Sets the tipo dia calendar local service.
	 *
	 * @param tipoDiaCalendarLocalService the tipo dia calendar local service
	 */
	public void setTipoDiaCalendarLocalService(
		es.davinciti.liferay.service.TipoDiaCalendarLocalService tipoDiaCalendarLocalService) {
		this.tipoDiaCalendarLocalService = tipoDiaCalendarLocalService;
	}

	/**
	 * Returns the tipo dia calendar remote service.
	 *
	 * @return the tipo dia calendar remote service
	 */
	public es.davinciti.liferay.service.TipoDiaCalendarService getTipoDiaCalendarService() {
		return tipoDiaCalendarService;
	}

	/**
	 * Sets the tipo dia calendar remote service.
	 *
	 * @param tipoDiaCalendarService the tipo dia calendar remote service
	 */
	public void setTipoDiaCalendarService(
		es.davinciti.liferay.service.TipoDiaCalendarService tipoDiaCalendarService) {
		this.tipoDiaCalendarService = tipoDiaCalendarService;
	}

	/**
	 * Returns the tipo dia calendar persistence.
	 *
	 * @return the tipo dia calendar persistence
	 */
	public TipoDiaCalendarPersistence getTipoDiaCalendarPersistence() {
		return tipoDiaCalendarPersistence;
	}

	/**
	 * Sets the tipo dia calendar persistence.
	 *
	 * @param tipoDiaCalendarPersistence the tipo dia calendar persistence
	 */
	public void setTipoDiaCalendarPersistence(
		TipoDiaCalendarPersistence tipoDiaCalendarPersistence) {
		this.tipoDiaCalendarPersistence = tipoDiaCalendarPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return LineaGastoProyecto.class;
	}

	protected String getModelClassName() {
		return LineaGastoProyecto.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = lineaGastoProyectoPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = es.davinciti.liferay.service.ApplicationStatusLocalService.class)
	protected es.davinciti.liferay.service.ApplicationStatusLocalService applicationStatusLocalService;
	@BeanReference(type = es.davinciti.liferay.service.ApplicationStatusService.class)
	protected es.davinciti.liferay.service.ApplicationStatusService applicationStatusService;
	@BeanReference(type = ApplicationStatusPersistence.class)
	protected ApplicationStatusPersistence applicationStatusPersistence;
	@BeanReference(type = es.davinciti.liferay.service.CalendarioLocalService.class)
	protected es.davinciti.liferay.service.CalendarioLocalService calendarioLocalService;
	@BeanReference(type = es.davinciti.liferay.service.CalendarioService.class)
	protected es.davinciti.liferay.service.CalendarioService calendarioService;
	@BeanReference(type = CalendarioPersistence.class)
	protected CalendarioPersistence calendarioPersistence;
	@BeanReference(type = es.davinciti.liferay.service.ConnectionActionTypesLocalService.class)
	protected es.davinciti.liferay.service.ConnectionActionTypesLocalService connectionActionTypesLocalService;
	@BeanReference(type = es.davinciti.liferay.service.ConnectionActionTypesService.class)
	protected es.davinciti.liferay.service.ConnectionActionTypesService connectionActionTypesService;
	@BeanReference(type = ConnectionActionTypesPersistence.class)
	protected ConnectionActionTypesPersistence connectionActionTypesPersistence;
	@BeanReference(type = es.davinciti.liferay.service.ConnectionConfigsLocalService.class)
	protected es.davinciti.liferay.service.ConnectionConfigsLocalService connectionConfigsLocalService;
	@BeanReference(type = es.davinciti.liferay.service.ConnectionConfigsService.class)
	protected es.davinciti.liferay.service.ConnectionConfigsService connectionConfigsService;
	@BeanReference(type = ConnectionConfigsPersistence.class)
	protected ConnectionConfigsPersistence connectionConfigsPersistence;
	@BeanReference(type = es.davinciti.liferay.service.ConnectionDataLocalService.class)
	protected es.davinciti.liferay.service.ConnectionDataLocalService connectionDataLocalService;
	@BeanReference(type = es.davinciti.liferay.service.ConnectionDataService.class)
	protected es.davinciti.liferay.service.ConnectionDataService connectionDataService;
	@BeanReference(type = ConnectionDataPersistence.class)
	protected ConnectionDataPersistence connectionDataPersistence;
	@BeanReference(type = es.davinciti.liferay.service.ConnectionTypesLocalService.class)
	protected es.davinciti.liferay.service.ConnectionTypesLocalService connectionTypesLocalService;
	@BeanReference(type = es.davinciti.liferay.service.ConnectionTypesService.class)
	protected es.davinciti.liferay.service.ConnectionTypesService connectionTypesService;
	@BeanReference(type = ConnectionTypesPersistence.class)
	protected ConnectionTypesPersistence connectionTypesPersistence;
	@BeanReference(type = es.davinciti.liferay.service.CurrenciesCompanyLocalService.class)
	protected es.davinciti.liferay.service.CurrenciesCompanyLocalService currenciesCompanyLocalService;
	@BeanReference(type = es.davinciti.liferay.service.CurrenciesCompanyService.class)
	protected es.davinciti.liferay.service.CurrenciesCompanyService currenciesCompanyService;
	@BeanReference(type = CurrenciesCompanyPersistence.class)
	protected CurrenciesCompanyPersistence currenciesCompanyPersistence;
	@BeanReference(type = es.davinciti.liferay.service.CurrencyLocalService.class)
	protected es.davinciti.liferay.service.CurrencyLocalService currencyLocalService;
	@BeanReference(type = es.davinciti.liferay.service.CurrencyService.class)
	protected es.davinciti.liferay.service.CurrencyService currencyService;
	@BeanReference(type = CurrencyPersistence.class)
	protected CurrencyPersistence currencyPersistence;
	@BeanReference(type = es.davinciti.liferay.service.DiasVacacionesLocalService.class)
	protected es.davinciti.liferay.service.DiasVacacionesLocalService diasVacacionesLocalService;
	@BeanReference(type = es.davinciti.liferay.service.DiasVacacionesService.class)
	protected es.davinciti.liferay.service.DiasVacacionesService diasVacacionesService;
	@BeanReference(type = DiasVacacionesPersistence.class)
	protected DiasVacacionesPersistence diasVacacionesPersistence;
	@BeanReference(type = es.davinciti.liferay.service.HistoricoNotaLocalService.class)
	protected es.davinciti.liferay.service.HistoricoNotaLocalService historicoNotaLocalService;
	@BeanReference(type = es.davinciti.liferay.service.HistoricoNotaService.class)
	protected es.davinciti.liferay.service.HistoricoNotaService historicoNotaService;
	@BeanReference(type = HistoricoNotaPersistence.class)
	protected HistoricoNotaPersistence historicoNotaPersistence;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoLocalService.class)
	protected es.davinciti.liferay.service.LineaGastoLocalService lineaGastoLocalService;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoService.class)
	protected es.davinciti.liferay.service.LineaGastoService lineaGastoService;
	@BeanReference(type = LineaGastoPersistence.class)
	protected LineaGastoPersistence lineaGastoPersistence;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoCategoriaLocalService.class)
	protected es.davinciti.liferay.service.LineaGastoCategoriaLocalService lineaGastoCategoriaLocalService;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoCategoriaService.class)
	protected es.davinciti.liferay.service.LineaGastoCategoriaService lineaGastoCategoriaService;
	@BeanReference(type = LineaGastoCategoriaPersistence.class)
	protected LineaGastoCategoriaPersistence lineaGastoCategoriaPersistence;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoClienteLocalService.class)
	protected es.davinciti.liferay.service.LineaGastoClienteLocalService lineaGastoClienteLocalService;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoClienteService.class)
	protected es.davinciti.liferay.service.LineaGastoClienteService lineaGastoClienteService;
	@BeanReference(type = LineaGastoClientePersistence.class)
	protected LineaGastoClientePersistence lineaGastoClientePersistence;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoFamiliaLocalService.class)
	protected es.davinciti.liferay.service.LineaGastoFamiliaLocalService lineaGastoFamiliaLocalService;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoFamiliaService.class)
	protected es.davinciti.liferay.service.LineaGastoFamiliaService lineaGastoFamiliaService;
	@BeanReference(type = LineaGastoFamiliaPersistence.class)
	protected LineaGastoFamiliaPersistence lineaGastoFamiliaPersistence;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoPayModeLocalService.class)
	protected es.davinciti.liferay.service.LineaGastoPayModeLocalService lineaGastoPayModeLocalService;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoPayModeService.class)
	protected es.davinciti.liferay.service.LineaGastoPayModeService lineaGastoPayModeService;
	@BeanReference(type = LineaGastoPayModePersistence.class)
	protected LineaGastoPayModePersistence lineaGastoPayModePersistence;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoProyectoLocalService.class)
	protected es.davinciti.liferay.service.LineaGastoProyectoLocalService lineaGastoProyectoLocalService;
	@BeanReference(type = es.davinciti.liferay.service.LineaGastoProyectoService.class)
	protected es.davinciti.liferay.service.LineaGastoProyectoService lineaGastoProyectoService;
	@BeanReference(type = LineaGastoProyectoPersistence.class)
	protected LineaGastoProyectoPersistence lineaGastoProyectoPersistence;
	@BeanReference(type = es.davinciti.liferay.service.NotaGastoLocalService.class)
	protected es.davinciti.liferay.service.NotaGastoLocalService notaGastoLocalService;
	@BeanReference(type = es.davinciti.liferay.service.NotaGastoService.class)
	protected es.davinciti.liferay.service.NotaGastoService notaGastoService;
	@BeanReference(type = NotaGastoPersistence.class)
	protected NotaGastoPersistence notaGastoPersistence;
	@BeanReference(type = es.davinciti.liferay.service.OrganizationSageCompanyLocalService.class)
	protected es.davinciti.liferay.service.OrganizationSageCompanyLocalService organizationSageCompanyLocalService;
	@BeanReference(type = es.davinciti.liferay.service.OrganizationSageCompanyService.class)
	protected es.davinciti.liferay.service.OrganizationSageCompanyService organizationSageCompanyService;
	@BeanReference(type = OrganizationSageCompanyPersistence.class)
	protected OrganizationSageCompanyPersistence organizationSageCompanyPersistence;
	@BeanReference(type = es.davinciti.liferay.service.SageEmployeeLocalService.class)
	protected es.davinciti.liferay.service.SageEmployeeLocalService sageEmployeeLocalService;
	@BeanReference(type = es.davinciti.liferay.service.SageEmployeeService.class)
	protected es.davinciti.liferay.service.SageEmployeeService sageEmployeeService;
	@BeanReference(type = SageEmployeePersistence.class)
	protected SageEmployeePersistence sageEmployeePersistence;
	@BeanReference(type = es.davinciti.liferay.service.SapEmployeeLocalService.class)
	protected es.davinciti.liferay.service.SapEmployeeLocalService sapEmployeeLocalService;
	@BeanReference(type = es.davinciti.liferay.service.SapEmployeeService.class)
	protected es.davinciti.liferay.service.SapEmployeeService sapEmployeeService;
	@BeanReference(type = SapEmployeePersistence.class)
	protected SapEmployeePersistence sapEmployeePersistence;
	@BeanReference(type = es.davinciti.liferay.service.TipoDiaCalendarLocalService.class)
	protected es.davinciti.liferay.service.TipoDiaCalendarLocalService tipoDiaCalendarLocalService;
	@BeanReference(type = es.davinciti.liferay.service.TipoDiaCalendarService.class)
	protected es.davinciti.liferay.service.TipoDiaCalendarService tipoDiaCalendarService;
	@BeanReference(type = TipoDiaCalendarPersistence.class)
	protected TipoDiaCalendarPersistence tipoDiaCalendarPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private LineaGastoProyectoServiceClpInvoker _clpInvoker = new LineaGastoProyectoServiceClpInvoker();
}