/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Calendario service. Represents a row in the &quot;CMES_Calendario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.CalendarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.CalendarioImpl}.
 * </p>
 *
 * @author Cmes
 * @see Calendario
 * @see es.davinciti.liferay.model.impl.CalendarioImpl
 * @see es.davinciti.liferay.model.impl.CalendarioModelImpl
 * @generated
 */
public interface CalendarioModel extends BaseModel<Calendario> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a calendario model instance should use the {@link Calendario} interface instead.
	 */

	/**
	 * Returns the primary key of this calendario.
	 *
	 * @return the primary key of this calendario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this calendario.
	 *
	 * @param primaryKey the primary key of this calendario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the calendario ID of this calendario.
	 *
	 * @return the calendario ID of this calendario
	 */
	public long getCalendarioId();

	/**
	 * Sets the calendario ID of this calendario.
	 *
	 * @param calendarioId the calendario ID of this calendario
	 */
	public void setCalendarioId(long calendarioId);

	/**
	 * Returns the company ID of this calendario.
	 *
	 * @return the company ID of this calendario
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this calendario.
	 *
	 * @param companyId the company ID of this calendario
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this calendario.
	 *
	 * @return the user ID of this calendario
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this calendario.
	 *
	 * @param userId the user ID of this calendario
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this calendario.
	 *
	 * @return the user uuid of this calendario
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this calendario.
	 *
	 * @param userUuid the user uuid of this calendario
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the year of this calendario.
	 *
	 * @return the year of this calendario
	 */
	public int getYear();

	/**
	 * Sets the year of this calendario.
	 *
	 * @param year the year of this calendario
	 */
	public void setYear(int year);

	/**
	 * Returns the calendar json of this calendario.
	 *
	 * @return the calendar json of this calendario
	 */
	@AutoEscape
	public String getCalendarJson();

	/**
	 * Sets the calendar json of this calendario.
	 *
	 * @param calendarJson the calendar json of this calendario
	 */
	public void setCalendarJson(String calendarJson);

	/**
	 * Returns the status of this calendario.
	 *
	 * @return the status of this calendario
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this calendario.
	 *
	 * @param status the status of this calendario
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(es.davinciti.liferay.model.Calendario calendario);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.Calendario> toCacheModel();

	@Override
	public es.davinciti.liferay.model.Calendario toEscapedModel();

	@Override
	public es.davinciti.liferay.model.Calendario toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}