/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ConnectionTypes service. Represents a row in the &quot;CMES_ConnectionTypes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.ConnectionTypesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.ConnectionTypesImpl}.
 * </p>
 *
 * @author Cmes
 * @see ConnectionTypes
 * @see es.davinciti.liferay.model.impl.ConnectionTypesImpl
 * @see es.davinciti.liferay.model.impl.ConnectionTypesModelImpl
 * @generated
 */
public interface ConnectionTypesModel extends BaseModel<ConnectionTypes> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a connection types model instance should use the {@link ConnectionTypes} interface instead.
	 */

	/**
	 * Returns the primary key of this connection types.
	 *
	 * @return the primary key of this connection types
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this connection types.
	 *
	 * @param primaryKey the primary key of this connection types
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the connection type ID of this connection types.
	 *
	 * @return the connection type ID of this connection types
	 */
	public long getConnectionTypeId();

	/**
	 * Sets the connection type ID of this connection types.
	 *
	 * @param connectionTypeId the connection type ID of this connection types
	 */
	public void setConnectionTypeId(long connectionTypeId);

	/**
	 * Returns the name of this connection types.
	 *
	 * @return the name of this connection types
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this connection types.
	 *
	 * @param name the name of this connection types
	 */
	public void setName(String name);

	/**
	 * Returns the disable date of this connection types.
	 *
	 * @return the disable date of this connection types
	 */
	public Date getDisableDate();

	/**
	 * Sets the disable date of this connection types.
	 *
	 * @param disableDate the disable date of this connection types
	 */
	public void setDisableDate(Date disableDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.ConnectionTypes connectionTypes);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.ConnectionTypes> toCacheModel();

	@Override
	public es.davinciti.liferay.model.ConnectionTypes toEscapedModel();

	@Override
	public es.davinciti.liferay.model.ConnectionTypes toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}