/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ConnectionConfigs service. Represents a row in the &quot;CMES_ConnectionConfigs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.ConnectionConfigsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.ConnectionConfigsImpl}.
 * </p>
 *
 * @author Cmes
 * @see ConnectionConfigs
 * @see es.davinciti.liferay.model.impl.ConnectionConfigsImpl
 * @see es.davinciti.liferay.model.impl.ConnectionConfigsModelImpl
 * @generated
 */
public interface ConnectionConfigsModel extends BaseModel<ConnectionConfigs> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a connection configs model instance should use the {@link ConnectionConfigs} interface instead.
	 */

	/**
	 * Returns the primary key of this connection configs.
	 *
	 * @return the primary key of this connection configs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this connection configs.
	 *
	 * @param primaryKey the primary key of this connection configs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the config ID of this connection configs.
	 *
	 * @return the config ID of this connection configs
	 */
	public long getConfigId();

	/**
	 * Sets the config ID of this connection configs.
	 *
	 * @param configId the config ID of this connection configs
	 */
	public void setConfigId(long configId);

	/**
	 * Returns the company ID of this connection configs.
	 *
	 * @return the company ID of this connection configs
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this connection configs.
	 *
	 * @param companyId the company ID of this connection configs
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the installation ID of this connection configs.
	 *
	 * @return the installation ID of this connection configs
	 */
	@AutoEscape
	public String getInstallationId();

	/**
	 * Sets the installation ID of this connection configs.
	 *
	 * @param installationId the installation ID of this connection configs
	 */
	public void setInstallationId(String installationId);

	/**
	 * Returns the company code of this connection configs.
	 *
	 * @return the company code of this connection configs
	 */
	@AutoEscape
	public String getCompanyCode();

	/**
	 * Sets the company code of this connection configs.
	 *
	 * @param companyCode the company code of this connection configs
	 */
	public void setCompanyCode(String companyCode);

	/**
	 * Returns the product code of this connection configs.
	 *
	 * @return the product code of this connection configs
	 */
	@AutoEscape
	public String getProductCode();

	/**
	 * Sets the product code of this connection configs.
	 *
	 * @param productCode the product code of this connection configs
	 */
	public void setProductCode(String productCode);

	/**
	 * Returns the disable date of this connection configs.
	 *
	 * @return the disable date of this connection configs
	 */
	public Date getDisableDate();

	/**
	 * Sets the disable date of this connection configs.
	 *
	 * @param disableDate the disable date of this connection configs
	 */
	public void setDisableDate(Date disableDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.ConnectionConfigs connectionConfigs);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.ConnectionConfigs> toCacheModel();

	@Override
	public es.davinciti.liferay.model.ConnectionConfigs toEscapedModel();

	@Override
	public es.davinciti.liferay.model.ConnectionConfigs toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}