/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CurrenciesCompany service. Represents a row in the &quot;CMES_CurrenciesCompany&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.CurrenciesCompanyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.CurrenciesCompanyImpl}.
 * </p>
 *
 * @author Cmes
 * @see CurrenciesCompany
 * @see es.davinciti.liferay.model.impl.CurrenciesCompanyImpl
 * @see es.davinciti.liferay.model.impl.CurrenciesCompanyModelImpl
 * @generated
 */
public interface CurrenciesCompanyModel extends BaseModel<CurrenciesCompany> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a currencies company model instance should use the {@link CurrenciesCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this currencies company.
	 *
	 * @return the primary key of this currencies company
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this currencies company.
	 *
	 * @param primaryKey the primary key of this currencies company
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the currenciescompany ID of this currencies company.
	 *
	 * @return the currenciescompany ID of this currencies company
	 */
	public long getCurrenciescompanyId();

	/**
	 * Sets the currenciescompany ID of this currencies company.
	 *
	 * @param currenciescompanyId the currenciescompany ID of this currencies company
	 */
	public void setCurrenciescompanyId(long currenciescompanyId);

	/**
	 * Returns the company ID of this currencies company.
	 *
	 * @return the company ID of this currencies company
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this currencies company.
	 *
	 * @param companyId the company ID of this currencies company
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the currencies json of this currencies company.
	 *
	 * @return the currencies json of this currencies company
	 */
	@AutoEscape
	public String getCurrenciesJson();

	/**
	 * Sets the currencies json of this currencies company.
	 *
	 * @param currenciesJson the currencies json of this currencies company
	 */
	public void setCurrenciesJson(String currenciesJson);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.CurrenciesCompany currenciesCompany);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.CurrenciesCompany> toCacheModel();

	@Override
	public es.davinciti.liferay.model.CurrenciesCompany toEscapedModel();

	@Override
	public es.davinciti.liferay.model.CurrenciesCompany toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}