/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Currency service. Represents a row in the &quot;CMES_Currency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.CurrencyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.CurrencyImpl}.
 * </p>
 *
 * @author Cmes
 * @see Currency
 * @see es.davinciti.liferay.model.impl.CurrencyImpl
 * @see es.davinciti.liferay.model.impl.CurrencyModelImpl
 * @generated
 */
public interface CurrencyModel extends BaseModel<Currency> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a currency model instance should use the {@link Currency} interface instead.
	 */

	/**
	 * Returns the primary key of this currency.
	 *
	 * @return the primary key of this currency
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this currency.
	 *
	 * @param primaryKey the primary key of this currency
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the currency ID of this currency.
	 *
	 * @return the currency ID of this currency
	 */
	public long getCurrencyId();

	/**
	 * Sets the currency ID of this currency.
	 *
	 * @param currencyId the currency ID of this currency
	 */
	public void setCurrencyId(long currencyId);

	/**
	 * Returns the ccy mnr unts of this currency.
	 *
	 * @return the ccy mnr unts of this currency
	 */
	@AutoEscape
	public String getCcyMnrUnts();

	/**
	 * Sets the ccy mnr unts of this currency.
	 *
	 * @param ccyMnrUnts the ccy mnr unts of this currency
	 */
	public void setCcyMnrUnts(String ccyMnrUnts);

	/**
	 * Returns the ccy name of this currency.
	 *
	 * @return the ccy name of this currency
	 */
	@AutoEscape
	public String getCcyName();

	/**
	 * Sets the ccy name of this currency.
	 *
	 * @param ccyName the ccy name of this currency
	 */
	public void setCcyName(String ccyName);

	/**
	 * Returns the ccy number of this currency.
	 *
	 * @return the ccy number of this currency
	 */
	@AutoEscape
	public String getCcyNumber();

	/**
	 * Sets the ccy number of this currency.
	 *
	 * @param ccyNumber the ccy number of this currency
	 */
	public void setCcyNumber(String ccyNumber);

	/**
	 * Returns the code of this currency.
	 *
	 * @return the code of this currency
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this currency.
	 *
	 * @param code the code of this currency
	 */
	public void setCode(String code);

	/**
	 * Returns the country name of this currency.
	 *
	 * @return the country name of this currency
	 */
	@AutoEscape
	public String getCountryName();

	/**
	 * Sets the country name of this currency.
	 *
	 * @param countryName the country name of this currency
	 */
	public void setCountryName(String countryName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(es.davinciti.liferay.model.Currency currency);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.Currency> toCacheModel();

	@Override
	public es.davinciti.liferay.model.Currency toEscapedModel();

	@Override
	public es.davinciti.liferay.model.Currency toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}