/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DiasVacaciones service. Represents a row in the &quot;CMES_DiasVacaciones&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.DiasVacacionesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.DiasVacacionesImpl}.
 * </p>
 *
 * @author Cmes
 * @see DiasVacaciones
 * @see es.davinciti.liferay.model.impl.DiasVacacionesImpl
 * @see es.davinciti.liferay.model.impl.DiasVacacionesModelImpl
 * @generated
 */
public interface DiasVacacionesModel extends BaseModel<DiasVacaciones> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dias vacaciones model instance should use the {@link DiasVacaciones} interface instead.
	 */

	/**
	 * Returns the primary key of this dias vacaciones.
	 *
	 * @return the primary key of this dias vacaciones
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dias vacaciones.
	 *
	 * @param primaryKey the primary key of this dias vacaciones
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dias vacaciones ID of this dias vacaciones.
	 *
	 * @return the dias vacaciones ID of this dias vacaciones
	 */
	public long getDiasVacacionesId();

	/**
	 * Sets the dias vacaciones ID of this dias vacaciones.
	 *
	 * @param diasVacacionesId the dias vacaciones ID of this dias vacaciones
	 */
	public void setDiasVacacionesId(long diasVacacionesId);

	/**
	 * Returns the company ID of this dias vacaciones.
	 *
	 * @return the company ID of this dias vacaciones
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dias vacaciones.
	 *
	 * @param companyId the company ID of this dias vacaciones
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dias vacaciones.
	 *
	 * @return the user ID of this dias vacaciones
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dias vacaciones.
	 *
	 * @param userId the user ID of this dias vacaciones
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dias vacaciones.
	 *
	 * @return the user uuid of this dias vacaciones
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dias vacaciones.
	 *
	 * @param userUuid the user uuid of this dias vacaciones
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the year of this dias vacaciones.
	 *
	 * @return the year of this dias vacaciones
	 */
	public int getYear();

	/**
	 * Sets the year of this dias vacaciones.
	 *
	 * @param year the year of this dias vacaciones
	 */
	public void setYear(int year);

	/**
	 * Returns the disponibles of this dias vacaciones.
	 *
	 * @return the disponibles of this dias vacaciones
	 */
	public int getDisponibles();

	/**
	 * Sets the disponibles of this dias vacaciones.
	 *
	 * @param disponibles the disponibles of this dias vacaciones
	 */
	public void setDisponibles(int disponibles);

	/**
	 * Returns the solicitados of this dias vacaciones.
	 *
	 * @return the solicitados of this dias vacaciones
	 */
	public int getSolicitados();

	/**
	 * Sets the solicitados of this dias vacaciones.
	 *
	 * @param solicitados the solicitados of this dias vacaciones
	 */
	public void setSolicitados(int solicitados);

	/**
	 * Returns the aprobados of this dias vacaciones.
	 *
	 * @return the aprobados of this dias vacaciones
	 */
	public int getAprobados();

	/**
	 * Sets the aprobados of this dias vacaciones.
	 *
	 * @param aprobados the aprobados of this dias vacaciones
	 */
	public void setAprobados(int aprobados);

	/**
	 * Returns the pendientes of this dias vacaciones.
	 *
	 * @return the pendientes of this dias vacaciones
	 */
	public int getPendientes();

	/**
	 * Sets the pendientes of this dias vacaciones.
	 *
	 * @param pendientes the pendientes of this dias vacaciones
	 */
	public void setPendientes(int pendientes);

	/**
	 * Returns the asignado of this dias vacaciones.
	 *
	 * @return the asignado of this dias vacaciones
	 */
	@AutoEscape
	public String getAsignado();

	/**
	 * Sets the asignado of this dias vacaciones.
	 *
	 * @param asignado the asignado of this dias vacaciones
	 */
	public void setAsignado(String asignado);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.DiasVacaciones diasVacaciones);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.DiasVacaciones> toCacheModel();

	@Override
	public es.davinciti.liferay.model.DiasVacaciones toEscapedModel();

	@Override
	public es.davinciti.liferay.model.DiasVacaciones toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}