/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LineaGastoCliente service. Represents a row in the &quot;CMES_LineaGastoCliente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.LineaGastoClienteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.LineaGastoClienteImpl}.
 * </p>
 *
 * @author Cmes
 * @see LineaGastoCliente
 * @see es.davinciti.liferay.model.impl.LineaGastoClienteImpl
 * @see es.davinciti.liferay.model.impl.LineaGastoClienteModelImpl
 * @generated
 */
public interface LineaGastoClienteModel extends BaseModel<LineaGastoCliente> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a linea gasto cliente model instance should use the {@link LineaGastoCliente} interface instead.
	 */

	/**
	 * Returns the primary key of this linea gasto cliente.
	 *
	 * @return the primary key of this linea gasto cliente
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this linea gasto cliente.
	 *
	 * @param primaryKey the primary key of this linea gasto cliente
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cliente ID of this linea gasto cliente.
	 *
	 * @return the cliente ID of this linea gasto cliente
	 */
	public long getClienteId();

	/**
	 * Sets the cliente ID of this linea gasto cliente.
	 *
	 * @param clienteId the cliente ID of this linea gasto cliente
	 */
	public void setClienteId(long clienteId);

	/**
	 * Returns the company ID of this linea gasto cliente.
	 *
	 * @return the company ID of this linea gasto cliente
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this linea gasto cliente.
	 *
	 * @param companyId the company ID of this linea gasto cliente
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this linea gasto cliente.
	 *
	 * @return the name of this linea gasto cliente
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this linea gasto cliente.
	 *
	 * @param name the name of this linea gasto cliente
	 */
	public void setName(String name);

	/**
	 * Returns the description of this linea gasto cliente.
	 *
	 * @return the description of this linea gasto cliente
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this linea gasto cliente.
	 *
	 * @param description the description of this linea gasto cliente
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.LineaGastoCliente lineaGastoCliente);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.LineaGastoCliente> toCacheModel();

	@Override
	public es.davinciti.liferay.model.LineaGastoCliente toEscapedModel();

	@Override
	public es.davinciti.liferay.model.LineaGastoCliente toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}