/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LineaGastoCategoria service. Represents a row in the &quot;CMES_LineaGastoCategoria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.LineaGastoCategoriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.LineaGastoCategoriaImpl}.
 * </p>
 *
 * @author Cmes
 * @see LineaGastoCategoria
 * @see es.davinciti.liferay.model.impl.LineaGastoCategoriaImpl
 * @see es.davinciti.liferay.model.impl.LineaGastoCategoriaModelImpl
 * @generated
 */
public interface LineaGastoCategoriaModel extends BaseModel<LineaGastoCategoria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a linea gasto categoria model instance should use the {@link LineaGastoCategoria} interface instead.
	 */

	/**
	 * Returns the primary key of this linea gasto categoria.
	 *
	 * @return the primary key of this linea gasto categoria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this linea gasto categoria.
	 *
	 * @param primaryKey the primary key of this linea gasto categoria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the categoria ID of this linea gasto categoria.
	 *
	 * @return the categoria ID of this linea gasto categoria
	 */
	public long getCategoriaId();

	/**
	 * Sets the categoria ID of this linea gasto categoria.
	 *
	 * @param categoriaId the categoria ID of this linea gasto categoria
	 */
	public void setCategoriaId(long categoriaId);

	/**
	 * Returns the name of this linea gasto categoria.
	 *
	 * @return the name of this linea gasto categoria
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this linea gasto categoria.
	 *
	 * @param name the name of this linea gasto categoria
	 */
	public void setName(String name);

	/**
	 * Returns the description of this linea gasto categoria.
	 *
	 * @return the description of this linea gasto categoria
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this linea gasto categoria.
	 *
	 * @param description the description of this linea gasto categoria
	 */
	public void setDescription(String description);

	/**
	 * Returns the category code of this linea gasto categoria.
	 *
	 * @return the category code of this linea gasto categoria
	 */
	@AutoEscape
	public String getCategoryCode();

	/**
	 * Sets the category code of this linea gasto categoria.
	 *
	 * @param categoryCode the category code of this linea gasto categoria
	 */
	public void setCategoryCode(String categoryCode);

	/**
	 * Returns the account code of this linea gasto categoria.
	 *
	 * @return the account code of this linea gasto categoria
	 */
	@AutoEscape
	public String getAccountCode();

	/**
	 * Sets the account code of this linea gasto categoria.
	 *
	 * @param accountCode the account code of this linea gasto categoria
	 */
	public void setAccountCode(String accountCode);

	/**
	 * Returns the change price of this linea gasto categoria.
	 *
	 * @return the change price of this linea gasto categoria
	 */
	@AutoEscape
	public String getChangePrice();

	/**
	 * Sets the change price of this linea gasto categoria.
	 *
	 * @param changePrice the change price of this linea gasto categoria
	 */
	public void setChangePrice(String changePrice);

	/**
	 * Returns the need quantity of this linea gasto categoria.
	 *
	 * @return the need quantity of this linea gasto categoria
	 */
	@AutoEscape
	public String getNeedQuantity();

	/**
	 * Sets the need quantity of this linea gasto categoria.
	 *
	 * @param needQuantity the need quantity of this linea gasto categoria
	 */
	public void setNeedQuantity(String needQuantity);

	/**
	 * Returns the price of this linea gasto categoria.
	 *
	 * @return the price of this linea gasto categoria
	 */
	@AutoEscape
	public String getPrice();

	/**
	 * Sets the price of this linea gasto categoria.
	 *
	 * @param price the price of this linea gasto categoria
	 */
	public void setPrice(String price);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.LineaGastoCategoria lineaGastoCategoria);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.LineaGastoCategoria> toCacheModel();

	@Override
	public es.davinciti.liferay.model.LineaGastoCategoria toEscapedModel();

	@Override
	public es.davinciti.liferay.model.LineaGastoCategoria toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}