/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LineaGastoPayMode service. Represents a row in the &quot;CMES_LineaGastoPayMode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.LineaGastoPayModeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.LineaGastoPayModeImpl}.
 * </p>
 *
 * @author Cmes
 * @see LineaGastoPayMode
 * @see es.davinciti.liferay.model.impl.LineaGastoPayModeImpl
 * @see es.davinciti.liferay.model.impl.LineaGastoPayModeModelImpl
 * @generated
 */
public interface LineaGastoPayModeModel extends BaseModel<LineaGastoPayMode> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a linea gasto pay mode model instance should use the {@link LineaGastoPayMode} interface instead.
	 */

	/**
	 * Returns the primary key of this linea gasto pay mode.
	 *
	 * @return the primary key of this linea gasto pay mode
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this linea gasto pay mode.
	 *
	 * @param primaryKey the primary key of this linea gasto pay mode
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the paymode ID of this linea gasto pay mode.
	 *
	 * @return the paymode ID of this linea gasto pay mode
	 */
	public long getPaymodeId();

	/**
	 * Sets the paymode ID of this linea gasto pay mode.
	 *
	 * @param paymodeId the paymode ID of this linea gasto pay mode
	 */
	public void setPaymodeId(long paymodeId);

	/**
	 * Returns the company ID of this linea gasto pay mode.
	 *
	 * @return the company ID of this linea gasto pay mode
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this linea gasto pay mode.
	 *
	 * @param companyId the company ID of this linea gasto pay mode
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this linea gasto pay mode.
	 *
	 * @return the name of this linea gasto pay mode
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this linea gasto pay mode.
	 *
	 * @param name the name of this linea gasto pay mode
	 */
	public void setName(String name);

	/**
	 * Returns the description of this linea gasto pay mode.
	 *
	 * @return the description of this linea gasto pay mode
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this linea gasto pay mode.
	 *
	 * @param description the description of this linea gasto pay mode
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.LineaGastoPayMode lineaGastoPayMode);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.LineaGastoPayMode> toCacheModel();

	@Override
	public es.davinciti.liferay.model.LineaGastoPayMode toEscapedModel();

	@Override
	public es.davinciti.liferay.model.LineaGastoPayMode toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}