/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LineaGastoProyecto service. Represents a row in the &quot;CMES_LineaGastoProyecto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.LineaGastoProyectoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.LineaGastoProyectoImpl}.
 * </p>
 *
 * @author Cmes
 * @see LineaGastoProyecto
 * @see es.davinciti.liferay.model.impl.LineaGastoProyectoImpl
 * @see es.davinciti.liferay.model.impl.LineaGastoProyectoModelImpl
 * @generated
 */
public interface LineaGastoProyectoModel extends BaseModel<LineaGastoProyecto> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a linea gasto proyecto model instance should use the {@link LineaGastoProyecto} interface instead.
	 */

	/**
	 * Returns the primary key of this linea gasto proyecto.
	 *
	 * @return the primary key of this linea gasto proyecto
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this linea gasto proyecto.
	 *
	 * @param primaryKey the primary key of this linea gasto proyecto
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the proyecto ID of this linea gasto proyecto.
	 *
	 * @return the proyecto ID of this linea gasto proyecto
	 */
	public long getProyectoId();

	/**
	 * Sets the proyecto ID of this linea gasto proyecto.
	 *
	 * @param proyectoId the proyecto ID of this linea gasto proyecto
	 */
	public void setProyectoId(long proyectoId);

	/**
	 * Returns the name of this linea gasto proyecto.
	 *
	 * @return the name of this linea gasto proyecto
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this linea gasto proyecto.
	 *
	 * @param name the name of this linea gasto proyecto
	 */
	public void setName(String name);

	/**
	 * Returns the description of this linea gasto proyecto.
	 *
	 * @return the description of this linea gasto proyecto
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this linea gasto proyecto.
	 *
	 * @param description the description of this linea gasto proyecto
	 */
	public void setDescription(String description);

	/**
	 * Returns the code name of this linea gasto proyecto.
	 *
	 * @return the code name of this linea gasto proyecto
	 */
	@AutoEscape
	public String getCodeName();

	/**
	 * Sets the code name of this linea gasto proyecto.
	 *
	 * @param codeName the code name of this linea gasto proyecto
	 */
	public void setCodeName(String codeName);

	/**
	 * Returns the sage company ID of this linea gasto proyecto.
	 *
	 * @return the sage company ID of this linea gasto proyecto
	 */
	@AutoEscape
	public String getSageCompanyId();

	/**
	 * Sets the sage company ID of this linea gasto proyecto.
	 *
	 * @param sageCompanyId the sage company ID of this linea gasto proyecto
	 */
	public void setSageCompanyId(String sageCompanyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.LineaGastoProyecto lineaGastoProyecto);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.LineaGastoProyecto> toCacheModel();

	@Override
	public es.davinciti.liferay.model.LineaGastoProyecto toEscapedModel();

	@Override
	public es.davinciti.liferay.model.LineaGastoProyecto toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}