/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SageEmployee service. Represents a row in the &quot;CMES_SageEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.SageEmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.SageEmployeeImpl}.
 * </p>
 *
 * @author Cmes
 * @see SageEmployee
 * @see es.davinciti.liferay.model.impl.SageEmployeeImpl
 * @see es.davinciti.liferay.model.impl.SageEmployeeModelImpl
 * @generated
 */
public interface SageEmployeeModel extends BaseModel<SageEmployee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sage employee model instance should use the {@link SageEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this sage employee.
	 *
	 * @return the primary key of this sage employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sage employee.
	 *
	 * @param primaryKey the primary key of this sage employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sage employee ID of this sage employee.
	 *
	 * @return the sage employee ID of this sage employee
	 */
	public long getSageEmployeeId();

	/**
	 * Sets the sage employee ID of this sage employee.
	 *
	 * @param sageEmployeeId the sage employee ID of this sage employee
	 */
	public void setSageEmployeeId(long sageEmployeeId);

	/**
	 * Returns the user ID of this sage employee.
	 *
	 * @return the user ID of this sage employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sage employee.
	 *
	 * @param userId the user ID of this sage employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sage employee.
	 *
	 * @return the user uuid of this sage employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this sage employee.
	 *
	 * @param userUuid the user uuid of this sage employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the employee i d of this sage employee.
	 *
	 * @return the employee i d of this sage employee
	 */
	@AutoEscape
	public String getEmployeeID();

	/**
	 * Sets the employee i d of this sage employee.
	 *
	 * @param employeeID the employee i d of this sage employee
	 */
	public void setEmployeeID(String employeeID);

	/**
	 * Returns the application ID of this sage employee.
	 *
	 * @return the application ID of this sage employee
	 */
	@AutoEscape
	public String getApplicationId();

	/**
	 * Sets the application ID of this sage employee.
	 *
	 * @param applicationId the application ID of this sage employee
	 */
	public void setApplicationId(String applicationId);

	/**
	 * Returns the company ID of this sage employee.
	 *
	 * @return the company ID of this sage employee
	 */
	@AutoEscape
	public String getCompanyId();

	/**
	 * Sets the company ID of this sage employee.
	 *
	 * @param companyId the company ID of this sage employee
	 */
	public void setCompanyId(String companyId);

	/**
	 * Returns the person ID of this sage employee.
	 *
	 * @return the person ID of this sage employee
	 */
	@AutoEscape
	public String getPersonId();

	/**
	 * Sets the person ID of this sage employee.
	 *
	 * @param personId the person ID of this sage employee
	 */
	public void setPersonId(String personId);

	/**
	 * Returns the start date of this sage employee.
	 *
	 * @return the start date of this sage employee
	 */
	@AutoEscape
	public String getStartDate();

	/**
	 * Sets the start date of this sage employee.
	 *
	 * @param startDate the start date of this sage employee
	 */
	public void setStartDate(String startDate);

	/**
	 * Returns the end date of this sage employee.
	 *
	 * @return the end date of this sage employee
	 */
	@AutoEscape
	public String getEndDate();

	/**
	 * Sets the end date of this sage employee.
	 *
	 * @param endDate the end date of this sage employee
	 */
	public void setEndDate(String endDate);

	/**
	 * Returns the seniority of this sage employee.
	 *
	 * @return the seniority of this sage employee
	 */
	@AutoEscape
	public String getSeniority();

	/**
	 * Sets the seniority of this sage employee.
	 *
	 * @param seniority the seniority of this sage employee
	 */
	public void setSeniority(String seniority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(es.davinciti.liferay.model.SageEmployee sageEmployee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.SageEmployee> toCacheModel();

	@Override
	public es.davinciti.liferay.model.SageEmployee toEscapedModel();

	@Override
	public es.davinciti.liferay.model.SageEmployee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}