/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SapEmployee service. Represents a row in the &quot;CMES_SapEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.SapEmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.SapEmployeeImpl}.
 * </p>
 *
 * @author Cmes
 * @see SapEmployee
 * @see es.davinciti.liferay.model.impl.SapEmployeeImpl
 * @see es.davinciti.liferay.model.impl.SapEmployeeModelImpl
 * @generated
 */
public interface SapEmployeeModel extends BaseModel<SapEmployee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sap employee model instance should use the {@link SapEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this sap employee.
	 *
	 * @return the primary key of this sap employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sap employee.
	 *
	 * @param primaryKey the primary key of this sap employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sap employee ID of this sap employee.
	 *
	 * @return the sap employee ID of this sap employee
	 */
	public long getSapEmployeeId();

	/**
	 * Sets the sap employee ID of this sap employee.
	 *
	 * @param sapEmployeeId the sap employee ID of this sap employee
	 */
	public void setSapEmployeeId(long sapEmployeeId);

	/**
	 * Returns the employee i d of this sap employee.
	 *
	 * @return the employee i d of this sap employee
	 */
	public long getEmployeeID();

	/**
	 * Sets the employee i d of this sap employee.
	 *
	 * @param employeeID the employee i d of this sap employee
	 */
	public void setEmployeeID(long employeeID);

	/**
	 * Returns the user ID of this sap employee.
	 *
	 * @return the user ID of this sap employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sap employee.
	 *
	 * @param userId the user ID of this sap employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sap employee.
	 *
	 * @return the user uuid of this sap employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this sap employee.
	 *
	 * @param userUuid the user uuid of this sap employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the middle name of this sap employee.
	 *
	 * @return the middle name of this sap employee
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this sap employee.
	 *
	 * @param middleName the middle name of this sap employee
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the gender of this sap employee.
	 *
	 * @return the gender of this sap employee
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this sap employee.
	 *
	 * @param gender the gender of this sap employee
	 */
	public void setGender(String gender);

	/**
	 * Returns the job title of this sap employee.
	 *
	 * @return the job title of this sap employee
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this sap employee.
	 *
	 * @param jobTitle the job title of this sap employee
	 */
	public void setJobTitle(String jobTitle);

	/**
	 * Returns the employee type of this sap employee.
	 *
	 * @return the employee type of this sap employee
	 */
	@AutoEscape
	public String getEmployeeType();

	/**
	 * Sets the employee type of this sap employee.
	 *
	 * @param employeeType the employee type of this sap employee
	 */
	public void setEmployeeType(String employeeType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(es.davinciti.liferay.model.SapEmployee sapEmployee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.SapEmployee> toCacheModel();

	@Override
	public es.davinciti.liferay.model.SapEmployee toEscapedModel();

	@Override
	public es.davinciti.liferay.model.SapEmployee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}