/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TipoDiaCalendar service. Represents a row in the &quot;CMES_TipoDiaCalendar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.davinciti.liferay.model.impl.TipoDiaCalendarModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.davinciti.liferay.model.impl.TipoDiaCalendarImpl}.
 * </p>
 *
 * @author Cmes
 * @see TipoDiaCalendar
 * @see es.davinciti.liferay.model.impl.TipoDiaCalendarImpl
 * @see es.davinciti.liferay.model.impl.TipoDiaCalendarModelImpl
 * @generated
 */
public interface TipoDiaCalendarModel extends BaseModel<TipoDiaCalendar> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipo dia calendar model instance should use the {@link TipoDiaCalendar} interface instead.
	 */

	/**
	 * Returns the primary key of this tipo dia calendar.
	 *
	 * @return the primary key of this tipo dia calendar
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipo dia calendar.
	 *
	 * @param primaryKey the primary key of this tipo dia calendar
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tipo dia calendar ID of this tipo dia calendar.
	 *
	 * @return the tipo dia calendar ID of this tipo dia calendar
	 */
	public long getTipoDiaCalendarId();

	/**
	 * Sets the tipo dia calendar ID of this tipo dia calendar.
	 *
	 * @param tipoDiaCalendarId the tipo dia calendar ID of this tipo dia calendar
	 */
	public void setTipoDiaCalendarId(long tipoDiaCalendarId);

	/**
	 * Returns the descripcion of this tipo dia calendar.
	 *
	 * @return the descripcion of this tipo dia calendar
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this tipo dia calendar.
	 *
	 * @param descripcion the descripcion of this tipo dia calendar
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the fondo color of this tipo dia calendar.
	 *
	 * @return the fondo color of this tipo dia calendar
	 */
	@AutoEscape
	public String getFondoColor();

	/**
	 * Sets the fondo color of this tipo dia calendar.
	 *
	 * @param fondoColor the fondo color of this tipo dia calendar
	 */
	public void setFondoColor(String fondoColor);

	/**
	 * Returns the letra color of this tipo dia calendar.
	 *
	 * @return the letra color of this tipo dia calendar
	 */
	@AutoEscape
	public String getLetraColor();

	/**
	 * Sets the letra color of this tipo dia calendar.
	 *
	 * @param letraColor the letra color of this tipo dia calendar
	 */
	public void setLetraColor(String letraColor);

	/**
	 * Returns the strong of this tipo dia calendar.
	 *
	 * @return the strong of this tipo dia calendar
	 */
	@AutoEscape
	public String getStrong();

	/**
	 * Sets the strong of this tipo dia calendar.
	 *
	 * @param strong the strong of this tipo dia calendar
	 */
	public void setStrong(String strong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		es.davinciti.liferay.model.TipoDiaCalendar tipoDiaCalendar);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.davinciti.liferay.model.TipoDiaCalendar> toCacheModel();

	@Override
	public es.davinciti.liferay.model.TipoDiaCalendar toEscapedModel();

	@Override
	public es.davinciti.liferay.model.TipoDiaCalendar toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}