/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import es.davinciti.liferay.model.ConnectionActionTypes;
import es.davinciti.liferay.model.ConnectionActionTypesModel;
import es.davinciti.liferay.model.ConnectionActionTypesSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ConnectionActionTypes service. Represents a row in the &quot;CMES_ConnectionActionTypes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link es.davinciti.liferay.model.ConnectionActionTypesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConnectionActionTypesImpl}.
 * </p>
 *
 * @author Cmes
 * @see ConnectionActionTypesImpl
 * @see es.davinciti.liferay.model.ConnectionActionTypes
 * @see es.davinciti.liferay.model.ConnectionActionTypesModel
 * @generated
 */
@JSON(strict = true)
public class ConnectionActionTypesModelImpl extends BaseModelImpl<ConnectionActionTypes>
	implements ConnectionActionTypesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a connection action types model instance should use the {@link es.davinciti.liferay.model.ConnectionActionTypes} interface instead.
	 */
	public static final String TABLE_NAME = "CMES_ConnectionActionTypes";
	public static final Object[][] TABLE_COLUMNS = {
			{ "connectionActionTypeId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "disableDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table CMES_ConnectionActionTypes (connectionActionTypeId LONG not null primary key,name VARCHAR(75) null,disableDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table CMES_ConnectionActionTypes";
	public static final String ORDER_BY_JPQL = " ORDER BY connectionActionTypes.connectionActionTypeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMES_ConnectionActionTypes.connectionActionTypeId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.es.davinciti.liferay.model.ConnectionActionTypes"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.es.davinciti.liferay.model.ConnectionActionTypes"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ConnectionActionTypes toModel(
		ConnectionActionTypesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ConnectionActionTypes model = new ConnectionActionTypesImpl();

		model.setConnectionActionTypeId(soapModel.getConnectionActionTypeId());
		model.setName(soapModel.getName());
		model.setDisableDate(soapModel.getDisableDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ConnectionActionTypes> toModels(
		ConnectionActionTypesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ConnectionActionTypes> models = new ArrayList<ConnectionActionTypes>(soapModels.length);

		for (ConnectionActionTypesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_CMES_CONFIGS_ACTIONS_NAME = "CMES_Configs_Actions";
	public static final Object[][] MAPPING_TABLE_CMES_CONFIGS_ACTIONS_COLUMNS = {
			{ "connectionActionTypeId", Types.BIGINT },
			{ "configId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_CMES_CONFIGS_ACTIONS_SQL_CREATE = "create table CMES_Configs_Actions (connectionActionTypeId LONG not null,configId LONG not null,primary key (connectionActionTypeId, configId))";
	public static final boolean FINDER_CACHE_ENABLED_CMES_CONFIGS_ACTIONS = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.CMES_Configs_Actions"), true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.es.davinciti.liferay.model.ConnectionActionTypes"));

	public ConnectionActionTypesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _connectionActionTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setConnectionActionTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _connectionActionTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ConnectionActionTypes.class;
	}

	@Override
	public String getModelClassName() {
		return ConnectionActionTypes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("connectionActionTypeId", getConnectionActionTypeId());
		attributes.put("name", getName());
		attributes.put("disableDate", getDisableDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long connectionActionTypeId = (Long)attributes.get(
				"connectionActionTypeId");

		if (connectionActionTypeId != null) {
			setConnectionActionTypeId(connectionActionTypeId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Date disableDate = (Date)attributes.get("disableDate");

		if (disableDate != null) {
			setDisableDate(disableDate);
		}
	}

	@JSON
	@Override
	public long getConnectionActionTypeId() {
		return _connectionActionTypeId;
	}

	@Override
	public void setConnectionActionTypeId(long connectionActionTypeId) {
		_connectionActionTypeId = connectionActionTypeId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public Date getDisableDate() {
		return _disableDate;
	}

	@Override
	public void setDisableDate(Date disableDate) {
		_disableDate = disableDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ConnectionActionTypes.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ConnectionActionTypes toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ConnectionActionTypes)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConnectionActionTypesImpl connectionActionTypesImpl = new ConnectionActionTypesImpl();

		connectionActionTypesImpl.setConnectionActionTypeId(getConnectionActionTypeId());
		connectionActionTypesImpl.setName(getName());
		connectionActionTypesImpl.setDisableDate(getDisableDate());

		connectionActionTypesImpl.resetOriginalValues();

		return connectionActionTypesImpl;
	}

	@Override
	public int compareTo(ConnectionActionTypes connectionActionTypes) {
		long primaryKey = connectionActionTypes.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ConnectionActionTypes)) {
			return false;
		}

		ConnectionActionTypes connectionActionTypes = (ConnectionActionTypes)obj;

		long primaryKey = connectionActionTypes.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ConnectionActionTypes> toCacheModel() {
		ConnectionActionTypesCacheModel connectionActionTypesCacheModel = new ConnectionActionTypesCacheModel();

		connectionActionTypesCacheModel.connectionActionTypeId = getConnectionActionTypeId();

		connectionActionTypesCacheModel.name = getName();

		String name = connectionActionTypesCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			connectionActionTypesCacheModel.name = null;
		}

		Date disableDate = getDisableDate();

		if (disableDate != null) {
			connectionActionTypesCacheModel.disableDate = disableDate.getTime();
		}
		else {
			connectionActionTypesCacheModel.disableDate = Long.MIN_VALUE;
		}

		return connectionActionTypesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{connectionActionTypeId=");
		sb.append(getConnectionActionTypeId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", disableDate=");
		sb.append(getDisableDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("es.davinciti.liferay.model.ConnectionActionTypes");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>connectionActionTypeId</column-name><column-value><![CDATA[");
		sb.append(getConnectionActionTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>disableDate</column-name><column-value><![CDATA[");
		sb.append(getDisableDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ConnectionActionTypes.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ConnectionActionTypes.class
		};
	private long _connectionActionTypeId;
	private String _name;
	private Date _disableDate;
	private ConnectionActionTypes _escapedModel;
}