/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.davinciti.liferay.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import es.davinciti.liferay.model.LineaGastoCliente;
import es.davinciti.liferay.model.LineaGastoClienteModel;
import es.davinciti.liferay.model.LineaGastoClienteSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LineaGastoCliente service. Represents a row in the &quot;CMES_LineaGastoCliente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link es.davinciti.liferay.model.LineaGastoClienteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LineaGastoClienteImpl}.
 * </p>
 *
 * @author Cmes
 * @see LineaGastoClienteImpl
 * @see es.davinciti.liferay.model.LineaGastoCliente
 * @see es.davinciti.liferay.model.LineaGastoClienteModel
 * @generated
 */
@JSON(strict = true)
public class LineaGastoClienteModelImpl extends BaseModelImpl<LineaGastoCliente>
	implements LineaGastoClienteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a linea gasto cliente model instance should use the {@link es.davinciti.liferay.model.LineaGastoCliente} interface instead.
	 */
	public static final String TABLE_NAME = "CMES_LineaGastoCliente";
	public static final Object[][] TABLE_COLUMNS = {
			{ "clienteId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CMES_LineaGastoCliente (clienteId LONG not null primary key,companyId LONG,name VARCHAR(75) null,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CMES_LineaGastoCliente";
	public static final String ORDER_BY_JPQL = " ORDER BY lineaGastoCliente.clienteId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CMES_LineaGastoCliente.clienteId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.es.davinciti.liferay.model.LineaGastoCliente"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.es.davinciti.liferay.model.LineaGastoCliente"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.es.davinciti.liferay.model.LineaGastoCliente"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long CLIENTEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LineaGastoCliente toModel(LineaGastoClienteSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LineaGastoCliente model = new LineaGastoClienteImpl();

		model.setClienteId(soapModel.getClienteId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LineaGastoCliente> toModels(
		LineaGastoClienteSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LineaGastoCliente> models = new ArrayList<LineaGastoCliente>(soapModels.length);

		for (LineaGastoClienteSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_CMES_LINEAS_CLIENTES_NAME = "CMES_Lineas_Clientes";
	public static final Object[][] MAPPING_TABLE_CMES_LINEAS_CLIENTES_COLUMNS = {
			{ "lineagastoId", Types.BIGINT },
			{ "clienteId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_CMES_LINEAS_CLIENTES_SQL_CREATE = "create table CMES_Lineas_Clientes (lineagastoId LONG not null,clienteId LONG not null,primary key (lineagastoId, clienteId))";
	public static final boolean FINDER_CACHE_ENABLED_CMES_LINEAS_CLIENTES = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.CMES_Lineas_Clientes"), true);
	public static final String MAPPING_TABLE_CMES_CLIENTES_PROYECTOS_NAME = "CMES_Clientes_Proyectos";
	public static final Object[][] MAPPING_TABLE_CMES_CLIENTES_PROYECTOS_COLUMNS =
		{
			{ "clienteId", Types.BIGINT },
			{ "proyectoId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_CMES_CLIENTES_PROYECTOS_SQL_CREATE = "create table CMES_Clientes_Proyectos (clienteId LONG not null,proyectoId LONG not null,primary key (clienteId, proyectoId))";
	public static final boolean FINDER_CACHE_ENABLED_CMES_CLIENTES_PROYECTOS = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.CMES_Clientes_Proyectos"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.es.davinciti.liferay.model.LineaGastoCliente"));

	public LineaGastoClienteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _clienteId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setClienteId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _clienteId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LineaGastoCliente.class;
	}

	@Override
	public String getModelClassName() {
		return LineaGastoCliente.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("clienteId", getClienteId());
		attributes.put("companyId", getCompanyId());
		attributes.put("name", getName());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long clienteId = (Long)attributes.get("clienteId");

		if (clienteId != null) {
			setClienteId(clienteId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@JSON
	@Override
	public long getClienteId() {
		return _clienteId;
	}

	@Override
	public void setClienteId(long clienteId) {
		_clienteId = clienteId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			LineaGastoCliente.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LineaGastoCliente toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LineaGastoCliente)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LineaGastoClienteImpl lineaGastoClienteImpl = new LineaGastoClienteImpl();

		lineaGastoClienteImpl.setClienteId(getClienteId());
		lineaGastoClienteImpl.setCompanyId(getCompanyId());
		lineaGastoClienteImpl.setName(getName());
		lineaGastoClienteImpl.setDescription(getDescription());

		lineaGastoClienteImpl.resetOriginalValues();

		return lineaGastoClienteImpl;
	}

	@Override
	public int compareTo(LineaGastoCliente lineaGastoCliente) {
		long primaryKey = lineaGastoCliente.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LineaGastoCliente)) {
			return false;
		}

		LineaGastoCliente lineaGastoCliente = (LineaGastoCliente)obj;

		long primaryKey = lineaGastoCliente.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LineaGastoClienteModelImpl lineaGastoClienteModelImpl = this;

		lineaGastoClienteModelImpl._originalCompanyId = lineaGastoClienteModelImpl._companyId;

		lineaGastoClienteModelImpl._setOriginalCompanyId = false;

		lineaGastoClienteModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LineaGastoCliente> toCacheModel() {
		LineaGastoClienteCacheModel lineaGastoClienteCacheModel = new LineaGastoClienteCacheModel();

		lineaGastoClienteCacheModel.clienteId = getClienteId();

		lineaGastoClienteCacheModel.companyId = getCompanyId();

		lineaGastoClienteCacheModel.name = getName();

		String name = lineaGastoClienteCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			lineaGastoClienteCacheModel.name = null;
		}

		lineaGastoClienteCacheModel.description = getDescription();

		String description = lineaGastoClienteCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			lineaGastoClienteCacheModel.description = null;
		}

		return lineaGastoClienteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{clienteId=");
		sb.append(getClienteId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("es.davinciti.liferay.model.LineaGastoCliente");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>clienteId</column-name><column-value><![CDATA[");
		sb.append(getClienteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LineaGastoCliente.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LineaGastoCliente.class
		};
	private long _clienteId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private String _name;
	private String _description;
	private long _columnBitmask;
	private LineaGastoCliente _escapedModel;
}